Repository PinkFlowerOfTheSunsetOfTheDeath/CMS, pull requests merged in 2018-06, with the labels that each got.

#24 Post - View a post (Back)
  composer.json
  core/binaries/pinkflowers.sql
  core/config/routing.yaml
  core/controllers/PostController.php
  core/helpers/Repository.php
  core/repositories/PostRepository.php
  core/views/posts/list.html.twig
  core/views/posts/view.html.twig
Labels: back

#27 Fix Entity Validation, clean post creation
  core/controllers/PostController.php
  core/entities/Post.php
  core/helpers/Entity.php
  core/helpers/ErrorManager.php
  public/index.php
Labels: back, back-office

#31 Connection front
  core/config/routing.yaml
  core/controllers/AuthController.php
  core/controllers/HelloController.php
  core/views/auth/login.html.twig
  core/views/auth/newAccount.html.twig
  core/views/hello.html.twig
  core/views/template/template.html.twig
  front/config.rb
  front/sass/global/_layout.scss
  front/sass/global/_variables.scss
  front/sass/pages/_connection.scss
  front/sass/styles.scss
  front/stylesheets/styles.css
  public/script/connection.js
  public/stylesheets/styles.css
Labels: back-office, front

#33 Authentication - User Login to back office
  composer.json
  core/config/routing.yaml
  core/controllers/AuthController.php
  core/controllers/PostController.php
  core/entities/User.php
  core/repositories/PostRepository.php
  core/repositories/UserRepository.php
Labels: back, back-office

#34 Create a Category - Back
  core/binaries/pinkflowers.sql
  core/config/routing.yaml
  core/controllers/CategoryController.php
  core/entities/Category.php
  core/repositories/CategoryRepository.php
  core/views/categories/form.html.twig
Labels: back, back-office

#40 Edit a Category - Back
  core/config/routing.yaml
  core/controllers/CategoryController.php
  core/repositories/CategoryRepository.php
  core/views/categories/form.html.twig
Labels: back, back-office

#43 View a Category - Back
  core/config/routing.yaml
  core/controllers/CategoryController.php
  core/views/categories/view.html.twig
Labels: back, back-office

#46 Article add
  core/helpers/Database.php
  core/views/auth/login.html.twig
  core/views/auth/newAccount.html.twig
  core/views/posts/list.html.twig
  core/views/template/template-no-nav.html.twig
  core/views/template/template.html.twig
  front/sass/components/_aside.scss
  front/sass/components/_header.scss
  front/sass/global/_fonts.scss
  front/sass/global/_layout.scss
  front/sass/global/_variables.scss
  front/sass/pages/_articleAdd.scss
  front/sass/styles.scss
  public/image/arrow.svg
  public/image/dashboard.svg
  public/image/eye-blind.svg
  public/image/eye.svg
  public/image/logo--mini.svg
  public/image/logo.svg
  public/image/page.svg
  public/image/paint.svg
  public/image/stylo.svg
  public/image/user.svg
  public/index.php
  public/script/aside.js
  public/script/createPost.js
  public/stylesheets/styles.css
Labels: back-office, front

#51 Configure Application - Boot / Run
  .gitignore
  composer.json
  core/boot/ConfigManager.php
  core/boot/Kernel.php
  core/boot/Router.php
  core/config/config.yaml
  core/helpers/Database.php
  public/index.php
Labels: back, configuration

#54 Configure theme for front office
  content/themes/default/home.php
  core/boot/ConfigManager.php
  core/boot/Kernel.php
  core/boot/ThemeManager.php
  core/helpers/Controller.php
Labels: back, configuration, front office

#59 Front Office - Home Page
  core/config/routing.yaml
  core/controllers/FrontController.php
  core/controllers/HelloController.php
Labels: back, front office

#61 Front office - View Article Page
  content/themes/default/404.php
  content/themes/default/article.php
  core/config/routing.yaml
  core/controllers/FrontController.php
  core/helpers/Controller.php
  core/repositories/PostRepository.php
Labels: back, front office

#62 Listing posts
  composer.lock
  core/controllers/PostController.php
  core/views/posts/form.html.twig
  core/views/posts/list.html.twig
  core/views/template/template.html.twig
  front/sass/components/_article.scss
  front/sass/components/_aside.scss
  front/sass/components/_header.scss
  front/sass/components/_table.scss
  front/sass/global/_layout.scss
  front/sass/global/_variables.scss
  front/sass/pages/_articleAdd.scss
  front/sass/pages/_articleList.scss
  front/sass/styles.scss
  public/script/createPost.js
  public/script/listingPost.js
  public/stylesheets/styles.css
Labels: back-office, front

#64 List Available custom themes in back office
  core/config/routing.yaml
  core/controllers/FrontController.php
  core/controllers/ThemeController.php
  core/entities/Theme.php
  core/helpers/Controller.php
  core/views/themes/list.html.twig
  public/content/themes/default/404.php
  public/content/themes/default/article.php
  public/content/themes/default/home.php
  public/content/themes/default/screenshot.jpg
Labels: back, back-office, themes

#71 Select Custom Theme - back office
  core/boot/ConfigManager.php
  core/boot/ThemeManager.php
  core/config/routing.yaml
  core/controllers/ThemeController.php
  core/entities/Theme.php
Labels: back, back-office, themes

#79 Auth - Login to back office
  core/binaries/pinkflowers.sql
  core/controllers/AuthController.php
  core/entities/User.php
  core/repositories/UserRepository.php
  core/views/auth/login.html.twig
Labels: authentication, back, back-office

#82 Authentication - Middleware
  core/boot/Kernel.php
  core/boot/Router.php
  core/config/config.yaml
  core/config/routing.yaml
  core/controllers/AuthController.php
  core/entities/User.php
  core/middlewares/AuthMiddleware.php
  core/views/auth/login.html.twig
  core/views/template/template-no-nav.html.twig
  core/views/template/template.html.twig
Labels: authentication, back, back-office

#84 Listing page
  core/views/pages/formPages.html.twig
  core/views/pages/listPages.html.twig
Labels: back-office, front

#92 Initialize Application on first login
  core/binaries/pinkflowers.sql
  core/boot/ConfigManager.php
  core/boot/Kernel.php
  core/config/routing.yaml
  core/controllers/InitController.php
  core/entities/Config.php
  core/entities/User.php
  core/helpers/Database.php
  core/repositories/UserRepository.php
  core/views/init/init.html.twig
  core/views/init/user.html.twig
Labels: back, back-office

#96 [FrontOffice/Page] Add handler for page view
  core/config/routing.yaml
  core/controllers/FrontController.php
  core/repositories/PageRepository.php
  public/content/themes/default/page.php
Labels: back, front office

#95 Listing page
  core/controllers/PageController.php
  core/controllers/PostController.php
  core/repositories/PageRepository.php
  core/views/pages/form.html.twig
  core/views/pages/formPages.html.twig
  core/views/pages/listPages.html.twig
  core/views/pages/viewPage.html.twig
  core/views/posts/form.html.twig
  core/views/posts/list.html.twig
  core/views/template/template.html.twig
  public/script/createPage.js
Labels: back-office, front

#97 Fix Auth - Logout from back office
  core/config/routing.yaml
  core/controllers/AuthController.php
  core/views/posts/form.html.twig
  core/views/posts/list.html.twig
  core/views/template/template.html.twig
Labels: authentication, back, back-office

#98 Pages - Edit a page
  core/config/routing.yaml
  core/controllers/PageController.php
  core/repositories/PageRepository.php
  core/views/pages/formPages.html.twig
  core/views/pages/listPages.html.twig
Labels: back, back-office

#100 Helper function - get_posts custom themes
  composer.json
  core/functions/posts.php
  core/repositories/PostRepository.php
Labels: back, back-office, front office

#101 Themes - List/Select
  core/controllers/ThemeController.php
  core/views/auth/login.html.twig
  core/views/auth/newAccount.html.twig
  core/views/pages/formPages.html.twig
  core/views/posts/form.html.twig
  core/views/posts/list.html.twig
  core/views/themes/list.html.twig
  front/sass/pages/_themes.scss
  public/script/listingPost.js
Labels: back-office, front
